site_name: learning k8s 
site_url: https://Lucia-Q.github.io/learn_k8s_single/

theme:
  name: material
  language: en           # UI 语言默认英文（Search/Previous/Next 等）

plugins:
  - search
  - i18n:
      docs_structure: suffix        # xxx.md（默认语言）/ xxx.zh.md（中文）
      languages:
        - locale: en
          name: English
          default: true             # ← 指定默认语言
          build: true               # ← 参与构建
        - locale: zh
          name: 简体中文
          build: true               # ← 参与构建
          # nav_translations:
          #   zh:
          #     Home: 首页
          #     Getting started: 快速开始

nav:
  - Home: index.md
  - Getting started: getting-started.md
  - case1: learn-k8s-django.md
